### ISSUE TITLE
The algorithm of instagram has been changed

### ISSUE THREAD

**Issue by Milor123** [CodeDotJS/instavim#4]
Hi dude, today instagram has implemented new change with the which we cant scrape profile pictures in full size... do you know about it?

If you know how bypass it, please write me :D

**Comment by CodeDotJS** [comment]
Hi, 

I'm trying to find some way to download the profile picture in full resolution. They made the changes a few hours ago and I've been working on it since so that I can find some way. 

This thing is tricky. Let's see what happens.

**Comment by ghost** [comment]
There is a new method to enlarge profile pictures: 
https://www.reddit.com/r/Instagram/comments/86l6w8/instagram_profile_picture/

xxC0dexx 8 points 3 days ago* 
Okay guys I found a final solution: Simply use my website ;) https://insta.justinlampe.de/ OR use this step by step guide:
1. Visit this page https://www.instagram.com/name/?__a=1 (replace name with the account name you are looking for)
2. This is a JSON-Code. Search for the user-id: graphql->user->id
3. Visit this API-Page https://i.instagram.com/api/v1/users/user-id/info/ and replace user-id with the id from step 2
4. This is a JSON-Code. Search for the link: user->hd_profile_pic_url_info->url This is the full size image.
Thats it! :)

**Comment by CodeDotJS** [comment]
Thanks for pointing out the solution! :heart: 

I've made the required changes and the tool works absolutely fine now!

**Comment by Milor123** [comment]
Wooow great, hahaha thank you guys !!! :D
